apiVersion: v1
kind: Service
metadata:
  name: classroom-optimizer
  labels:
    app: classroom-optimizer
spec:
  type: ClusterIP
  ports:
  - port: 7070
    targetPort: 7070
    protocol: TCP
    name: http
  selector:
    app: classroom-optimizer

